[package]
name = "openfhe-wrapper"
version = "0.1.0"
edition = "2021"
links = "openfhe-wrapper"


[build-dependencies]
bindgen = "0.65"
cmake = "0.1"

[dependencies]
openfhe-sys = { version = "*", path = "../openfhe-sys" }
